version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: student-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: student_management
    volumes:
      - ./Backend/Database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - student-network

  # Spring Boot Backend
  backend:
    build:
      context: ./Backend/spring-boot-app
      dockerfile: Dockerfile
    container_name: student-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/student_management
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    networks:
      - student-network

  # Frontend (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: student-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8081/api
    depends_on:
      - backend
    networks:
      - student-network

volumes:
  postgres_data:

networks:
  student-network:
    driver: bridge 